name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./ noticeboard/pom.xml
          mvn clean package -f ./agent/pom.xml
          mvn clean package -f ./admin/pom.xml
          mvn clean package -f ./platform/pom.xml

      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Noticeboard
        uses: docker/build-push-action@v4
        with:
          context: ./ noticeboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/-noticeboard:latest
            ghcr.io/${{ github.repository }}/-noticeboard:${{ github.ref_name }}
            
      - name: Docker Build and push for Agent
        uses: docker/build-push-action@v4
        with:
          context: ./agent
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/agent:latest
            ghcr.io/${{ github.repository }}/agent:${{ github.ref_name }}
            
      - name: Docker Build and push for Admin
        uses: docker/build-push-action@v4
        with:
          context: ./admin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/admin:latest
            ghcr.io/${{ github.repository }}/admin:${{ github.ref_name }}
            
      - name: Docker Build and push for Platform
        uses: docker/build-push-action@v4
        with:
          context: ./platform
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/platform:latest
            ghcr.io/${{ github.repository }}/platform:${{ github.ref_name }}
            
