apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-agent
  labels:
    app: orchestrator-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-agent
  template:
    metadata:
      labels:
        app: orchestrator-agent
    spec:
      containers:
        - name: orchestrator-agent
          image: leeyumin/orchestrator-agent:test
          ports:
            - containerPort: 8002
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
